# Generated by Django 2.1 on 2018-09-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('oid', models.UUIDField(unique=True)),
                ('pid', models.CharField(max_length=50)),
                ('appliance_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.UUIDField(unique=True)),
                ('unit', models.CharField(max_length=50)),
                ('element', models.CharField(max_length=50)),
                ('pid', models.CharField(max_length=50)),
            ],
        ),
    ]
