# Generated by Django 2.1 on 2018-09-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='monitors',
            field=models.CharField(choices=[('W', 'water'), ('P', 'power')], default='W', max_length=1),
            preserve_default=False,
        ),
    ]
